### ISSUE TITLE
The Story behind DDCM

### ISSUE THREAD

**Issue by skyzh** [SkyZH/ddcm-protocol#8]
When I was a 10th grade high school student, I proposed this project "A Decentralized P2P Distributed Computing Protocol". Now 4 years have passed by, and I'm still interested in making distributed systems and do system programming.

In this project I mainly did three things.

1. Implement a Kademlia protocol in TCP with Python asyncio framework.
2. Implement git-like increment storage on distributed key-value storage.
3. Propose a way to batch collect result on distributed network.

And I ran an experiment to count words on a website with this protocol. This repo can be found in ddcm-word-count in my GitHub.

Some ideas might seem immature and trivial, but I think that was a good attempt towards distributed system for me four years ago.

Here I also share some resource on this project.

[Submitted paper](https://github.com/skyzh/ddcm-protocol/files/4532296/paper-ddcm.pdf)
[Poster](https://github.com/skyzh/ddcm-protocol/files/4532297/poster-ddcm.pdf)

**Comment by xxchan** [comment]
too admirable!

**Comment by WenBiming** [comment]
Successful
